[package]
name = "adventofcode2019"
version = "0.1.0"
authors = ["Justin Thein <jthein@berkeley.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
